const q = (prompt, options, correctIndex, explanation) => ({ prompt, options, correctIndex, explanation })

export const tier3QuestionBanks = {
  platforms: [
    q('A manufacturer must keep a safety process operating when its internet connection fails. Which architecture decision best supports that requirement?',['Keep safety-critical control local with autonomous operation','Move every control decision to a public cloud API','Require remote users to share an administrator account','Route office traffic through the controller network'],0,'Local autonomous control avoids making WAN or cloud availability a dependency of the safety process.'),
    q('A legacy industrial controller cannot run endpoint agents or receive monthly patches. Which design best reduces its exposure?',['Place it in a restricted control zone with monitored conduits','Connect it directly to the corporate wireless network','Install unsupported security software','Expose its management service for easier support'],0,'Segmentation and tightly controlled communication reduce reachability without violating vendor or real-time constraints.'),
    q('Which cloud characteristic most directly changes who performs physical hardware maintenance?',['The provider operates the underlying facility and hardware','The customer no longer owns its data','Every application becomes serverless','Identity controls are unnecessary'],0,'Cloud service providers generally operate the physical infrastructure, while customer duties vary by service model.'),
    q('A team wants repeatable environments whose network and security settings are reviewed like source code. Which approach best fits?',['Infrastructure as code','Manual console changes without records','A larger virtual machine only','Shared local administrator passwords'],0,'Infrastructure as code makes environment configuration versioned, reviewable, testable, and repeatable.'),
    q('A short-lived event processor should scale per request without administrators managing servers. Which model is most appropriate?',['Serverless computing','Dedicated physical isolation','A permanently active desktop','An unsupported embedded controller'],0,'Serverless platforms execute functions on demand while the provider manages server provisioning and scaling.'),
    q('Several application components must deploy independently and communicate through defined interfaces. Which architecture is being described?',['Microservices','One monolithic process only','Air-gapped control','Cold-site recovery'],0,'Microservices separate capabilities into independently deployable services connected through explicit interfaces.'),
    q('What is the primary security value of container isolation?',['Processes receive separated runtime environments with constrained resources','Containers eliminate all kernel risk','Every container includes a separate physical server','Container images never require patching'],0,'Containers constrain processes and resources, but still share host components and require secure images and runtime controls.'),
    q('A guest operating system exploits a hypervisor flaw and accesses another guest. What vulnerability does this illustrate?',['Virtual machine escape','DNS poisoning','Password spraying','Tokenization'],0,'VM escape crosses the intended virtualization boundary from a guest into the host or another guest.'),
    q('A hospital device has fixed-purpose firmware, limited memory, and a long replacement cycle. Which risk is most important in its architecture?',['Limited patch availability over an extended service life','Unlimited elastic scaling','Frequent operating-system replacement','Automatic geographic failover'],0,'Embedded and IoT devices often remain deployed for years with limited update support, making exposure control and lifecycle planning essential.'),
    q('Which property distinguishes many real-time operating systems from ordinary business operating systems?',['They prioritize deterministic response deadlines','They always run in public clouds','They cannot control physical processes','They automatically provide zero trust'],0,'RTOS designs prioritize predictable timing because delayed responses can break operational or safety requirements.'),
    q('A company separates a research network using firewall policy but shares the same switching hardware. What kind of separation is this?',['Logical segmentation','Physical air gap','Geographic dispersion','Platform diversity'],0,'Logical segmentation uses policy and virtual boundaries on shared infrastructure rather than physical disconnection.'),
    q('When is an air gap most defensible?',['When a critical system requires physical isolation and controlled transfer despite operational friction','When users need unrestricted internet browsing','When cloud elasticity is the main goal','When remote administration must be effortless'],0,'Air gaps trade convenience and rapid data exchange for strong physical separation of highly critical systems.'),
    q('A service must remain available after one compute node fails. Which architecture characteristic directly addresses this?',['High availability with redundant instances and failover','A single larger node with no standby','Longer password expiration','Data masking'],0,'High availability uses redundancy and failover so one component failure does not stop the service.'),
    q('A hybrid application retains regulated records on premises but bursts anonymized processing into cloud capacity. What consideration drives this design?',['Balancing data obligations with elastic compute needs','Eliminating all shared responsibility','Making patching impossible','Removing the need for secure connectivity'],0,'Hybrid design can keep constrained data in a controlled location while using cloud scale for permitted processing.'),
    q('Two architectures meet security requirements. One recovers quickly but costs substantially more. What should the decision document?',['The explicit tradeoff among availability, recovery, risk, and cost','Only the least expensive monthly price','A claim that security has no cost','The number of vendor marketing features'],0,'Architecture selection should make business tradeoffs explicit rather than treating one quality as the only decision factor.'),
  ],
}
