export const tier5Lessons = {
  governance:{headings:["Turn intent into enforceable direction","Assign accountable ownership","Govern change and exceptions","Separate incompatible duties","Demonstrate care and diligence","Report risk to leadership"],content:[
    "Governance connects organizational goals to security decisions, authority, and accountability. Policies state required direction, standards define mandatory detail, procedures describe repeatable work, and guidelines offer flexible advice. These documents should form a coherent hierarchy instead of contradicting or duplicating one another.",
    "Named ownership prevents controls from disappearing between teams. Data owners decide classification and permitted use; system owners remain accountable for operation and risk. Control operators may perform daily work, but accountability stays with the role authorized to accept priorities, resources, and residual exposure.",
    "Change management evaluates risk, testing, approval, implementation, rollback, and post-change evidence. Exceptions provide time-bound, documented departures when direct compliance is impractical. An exception is not permission to forget the requirement; it needs an owner, compensating controls, expiration, and periodic review.",
    "Separation of duties divides incompatible powers such as requesting, approving, implementing, and reviewing a sensitive change. Small organizations may use compensating review, strong logging, or dual authorization when staffing prevents perfect separation. Shared credentials undermine the evidence these controls depend upon.",
    "Due diligence is the investigation that supports a decision; due care is the reasonable action taken after risks are understood. A company that assesses a supplier but ignores material findings performed investigation without responsible follow-through. Governance requires both informed decisions and evidence of implementation.",
    "Board and executive oversight should focus on material risk, strategy, ownership, trends, and choices—not raw alert counts. Effective reporting explains business impact, current controls, residual risk, requested decisions, and who will act by when. Leaders need enough evidence to govern without being buried in operational noise."
  ]},
  risk:{headings:["Define appetite and tolerance","Record risk explicitly","Separate inherent and residual risk","Choose a treatment","Use quantitative estimates carefully","Keep ownership and reporting alive"],content:[
    "Risk appetite describes the types and amount of risk an organization is willing to pursue or retain in support of objectives. Tolerance translates that broad direction into specific acceptable variation, such as maximum outage, fraud loss, or overdue critical findings. Teams should not invent tolerance during an incident.",
    "A risk register turns concerns into managed decisions. Each entry should describe the event, cause, affected objective, likelihood, impact, owner, treatment, target date, controls, residual risk, and status. Vague entries such as “cyberattack” are difficult to treat because they do not describe a decision-ready scenario.",
    "Inherent risk exists before additional safeguards; residual risk remains after controls operate. Control design alone does not prove residual risk is low. Evidence of effectiveness, exceptions, coverage gaps, and changing threats belongs in the analysis.",
    "Avoidance stops the risk-producing activity. Mitigation reduces likelihood or impact. Transfer shifts defined consequences through contracts or insurance but rarely transfers accountability. Acceptance is an authorized decision to retain understood residual risk. The treatment should match business objectives rather than defaulting to whichever control is familiar.",
    "Quantitative analysis can estimate single loss expectancy, annual rate of occurrence, and annual loss expectancy. These values support comparison, but uncertain inputs should be presented as ranges or scenarios rather than false precision. Qualitative rankings remain useful when reliable monetary evidence is unavailable.",
    "The risk owner monitors treatment and escalates change. Reports should show aging, control performance, concentration, overdue actions, and movement relative to tolerance. A register that is updated only before an audit is an archive, not a management system."
  ]},
  "third-party":{headings:["Assess before commitment","Put requirements in contracts","Understand dependency chains","Confront concentration","Monitor material change","Plan the exit before entry"],content:[
    "Supplier due diligence examines the service, data, access, architecture, financial stability, control evidence, incident history, and subcontractors before commitment. Assessment depth should follow criticality: a payroll processor deserves more scrutiny than a vendor receiving no sensitive data or system access.",
    "Contracts convert expectations into enforceable duties. SLAs define measurable service targets and remedies; NDAs restrict disclosure; data-processing agreements assign privacy responsibilities. Right-to-audit, security requirements, data location, deletion, and breach-notification timing should be settled before an incident exposes ambiguity.",
    "Third parties depend on fourth parties, software components, cloud platforms, and update channels. Supply-chain review asks not only whether the direct vendor is secure, but what hidden dependencies can affect confidentiality, integrity, availability, or recovery. An SBOM can improve component visibility without proving that every component is safe.",
    "Concentration risk appears when many critical services rely on one provider, region, identity platform, or shared component. A provider can have strong controls and still become a systemic point of failure. Architecture, contractual commitments, alternate suppliers, and tested recovery options should reflect that dependency.",
    "Assurance is continuous. Attestations and assessments are time-bounded evidence, not permanent guarantees. Teams should monitor incidents, ownership changes, financial condition, product changes, control exceptions, service performance, and expiring evidence, then reassess when material conditions change.",
    "An exit plan identifies data export formats, transition assistance, dependency replacement, access revocation, retention, verified deletion, and business continuity. Waiting until termination to discover proprietary formats or missing backups gives the supplier leverage and creates security risk during a rushed migration."
  ]},
  compliance:{headings:["Map obligations to controls","Protect privacy through the lifecycle","Distinguish audits and assessments","Authorize security testing","Manage findings to closure","Prepare reporting evidence"],content:[
    "Compliance brings together legal, regulatory, contractual, and internal requirements. Teams should map obligations to controls, owners, evidence, frequency, and systems in scope. Passing one audit does not prove universal compliance because criteria, populations, and dates differ.",
    "Privacy governs appropriate collection, purpose, use, disclosure, retention, access, and protection of personal data. Data controllers determine purposes and means; processors act on their behalf under defined instructions. Security controls support privacy, but encryption alone does not authorize unnecessary collection or use.",
    "An audit independently compares evidence with defined criteria. An assessment may evaluate control design, operation, risk, or readiness with varying independence. Penetration tests demonstrate exploitable paths and impact. The right method depends on the question the organization needs answered.",
    "Security testing requires written authorization and rules of engagement defining scope, timing, contacts, prohibited actions, data handling, and stop conditions. A technically skilled test without authorization can create legal and operational harm. Independence and conflicts of interest should also be considered.",
    "Findings describe the gap between required and observed state. A remediation plan names actions, owner, due date, validation, and dependencies. Compensating controls must meet the intended objective, not merely add unrelated security. Closure requires evidence that the implemented state changed.",
    "Regulatory reporting depends on triggers, timelines, affected data, jurisdiction, and confidence. Organizations should preserve evidence and involve legal and privacy owners early rather than waiting for complete certainty. Prepared templates and decision paths help meet deadlines without making unsupported claims."
  ]},
  awareness:{headings:["Target behavior, not attendance","Match learning to roles","Design ethical simulations","Make reporting easy","Reinforce and remediate","Measure outcomes that matter"],content:[
    "Awareness helps people recognize risk and expected behavior; training develops task-specific skills; education builds deeper transferable understanding. Completion records prove delivery, not behavior change. Programs should begin with the decisions people need to make and the errors that create meaningful risk.",
    "Role-based training reflects exposure and responsibility. Developers need secure design and dependency practices; finance needs payment verification; administrators need privileged-access handling; executives need crisis and risk decisions. Generic annual content should not be the only instruction for high-risk roles.",
    "Phishing simulations should measure and improve reporting, verification, and handling without humiliating participants. Lures should be approved, proportionate, privacy-aware, and accompanied by timely teaching. Click rate alone can mislead because reporting behavior and speed often matter more.",
    "Employees need a simple, visible reporting path with rapid feedback. Positive reinforcement makes future reporting more likely, including when the message turns out benign. Punitive cultures suppress weak signals and increase attacker dwell time.",
    "Just-in-time guidance appears near a decision, while remedial training addresses a demonstrated gap. Security champions translate program goals into local workflows and surface friction. Insider-risk awareness should teach observable concerning behavior and safe reporting without encouraging unsupported accusations.",
    "Useful metrics connect learning to outcomes: report rate, reporting speed, repeat susceptibility, help-desk patterns, policy exceptions, secure-development findings, and role-specific performance. Leaders should look for sustained improvement and control impact rather than chasing a perfect simulation score."
  ]},
  "resilience-program":{headings:["Start with business impact","Set coherent recovery targets","Separate continuity and recovery","Coordinate crisis leadership","Protect critical people and knowledge","Use metrics and exercises to drive decisions"],content:[
    "A business impact analysis identifies critical processes, disruption consequences, dependencies, peak periods, workarounds, and resource needs. The maximum tolerable duration defines the outer business limit. Technology targets should be derived from this analysis rather than selected because a platform advertises fast recovery.",
    "Recovery time objective defines the target restoration time; recovery point objective defines acceptable data loss. Both must be consistent with the maximum tolerable duration and with dependencies. A ten-minute application RTO is meaningless if identity, networking, or a supplier requires eight hours.",
    "Business continuity sustains critical operations through disruption using alternate processes, people, facilities, suppliers, and communications. Disaster recovery restores technology and data. A recovered server does not mean the business process is operating, and a manual workaround may sustain operations before technology returns.",
    "Crisis management coordinates executive decisions, priorities, external communications, legal obligations, and scarce resources during high-impact events. Plans should define authority and escalation while leaving room for judgment. Succession planning prevents one leader or specialist from becoming an undocumented single point of failure.",
    "Critical knowledge, credentials, supplier contacts, and decision authority should survive personnel unavailability. Cross-training and protected documentation reduce dependence on one expert. Emergency access must be controlled and tested rather than improvised when normal identity systems are unavailable.",
    "KPIs show progress toward desired performance; KRIs signal rising exposure. Leading indicators suggest future conditions, while lagging indicators describe outcomes already observed. Exercises test assumptions, reveal dependencies, and produce owned improvements. Executive communication should summarize impact, choices, ownership, timelines, and residual risk."
  ]},
}
