export const ciaTriadReading = [
  'The CIA triad is a compact way to describe what information security is trying to preserve: confidentiality, integrity, and availability. It is not a product checklist. It is a reasoning model. When a scenario describes a security problem, ask which property is being harmed and which safeguards would protect that property. Many incidents affect more than one part of the triad, but exam questions usually emphasize the primary concern.',
  'Confidentiality means information is disclosed only to authorized people, processes, and systems. Access controls, encryption, data classification, and need-to-know rules support confidentiality. A confidentiality failure can be obvious, such as a stolen customer database, or subtle, such as an employee viewing payroll records without a business reason. Privacy overlaps with confidentiality, but privacy focuses on appropriate collection and use of personal information, not only preventing disclosure.',
  'Integrity means information and systems remain accurate, complete, and trustworthy. An integrity failure occurs when data is changed without authorization or when people cannot verify that it is correct. Hashes can reveal that a file changed, digital signatures can provide integrity and source assurance, and permissions can prevent unauthorized modification. Backups may restore trusted data, while change management reduces accidental or unreviewed changes.',
  'Availability means authorized users can access systems and information when required. Redundancy, fault tolerance, backups, capacity planning, patching, and disaster recovery support availability. Threats include denial-of-service attacks, ransomware, hardware failure, power loss, and human error. Availability does not mean a system can never fail; it means the organization understands required uptime and designs recovery around business needs.',
  'Security decisions often involve tradeoffs between the three properties. Strong encryption can protect confidentiality but may reduce availability if key management fails. Aggressive access restrictions can reduce exposure but also prevent legitimate work. Replication improves availability but creates more copies that must remain confidential and accurate. Good design does not maximize one property in isolation—it balances all three according to risk and business requirements.',
  'Use the scenario’s outcome to identify the primary property. Unauthorized viewing points to confidentiality. Unauthorized or undetected modification points to integrity. Inability to reach a needed resource points to availability. Then look for the most direct safeguard. Encryption protects confidentiality, hashing detects integrity changes, and redundancy supports availability. This mapping is simple, but it becomes a powerful anchor for architecture, operations, incident response, and risk questions throughout Security+.',
]

export const ciaTriadCards = [
  ['CIA triad', 'A model describing confidentiality, integrity, and availability as core security objectives.'],
  ['Confidentiality', 'Information is disclosed only to authorized people, processes, and systems.'],
  ['Integrity', 'Information and systems remain accurate, complete, and trustworthy.'],
  ['Availability', 'Authorized users can access required systems and information when needed.'],
  ['Data breach', 'An incident involving unauthorized access to or disclosure of protected information.'],
  ['Hash', 'A one-way digest commonly used to detect whether data has changed.'],
  ['Digital signature', 'A cryptographic mechanism providing integrity, source authentication, and non-repudiation.'],
  ['Redundancy', 'Duplicate components or paths that reduce a single point of failure.'],
  ['Fault tolerance', 'The ability to continue operating when a component fails.'],
  ['Need to know', 'Access is limited to information required for an authorized task.'],
  ['Data classification', 'Labeling information according to sensitivity and handling requirements.'],
  ['Privacy', 'Appropriate collection, processing, retention, and use of personal information.'],
  ['Single point of failure', 'A component whose failure can make an entire service unavailable.'],
  ['Security tradeoff', 'A decision balancing protection, usability, cost, performance, and business requirements.'],
]

export const ciaTriadKnowledgeCheck = [
  { id: 'cia-kc-1', objective: '1.2', domain: 1, prompt: 'An unauthorized employee reads another worker’s salary information but does not change it. Which property was violated?', options: ['Availability', 'Integrity', 'Confidentiality', 'Non-repudiation'], correctIndex: 2, explanation: 'The information was disclosed to someone without authorization, so confidentiality was violated even though the data remained unchanged.' },
  { id: 'cia-kc-2', objective: '1.2', domain: 1, prompt: 'Which technology most directly helps verify that a downloaded file has not changed?', options: ['Load balancer', 'Hash', 'Full-disk encryption', 'Access badge'], correctIndex: 1, explanation: 'Comparing a trusted hash with the downloaded file’s hash can reveal modification, directly supporting integrity.' },
  { id: 'cia-kc-3', objective: '1.2', domain: 1, prompt: 'A web service continues operating after one server fails because traffic moves to another server. Which property is primarily supported?', options: ['Confidentiality', 'Availability', 'Integrity', 'Privacy'], correctIndex: 1, explanation: 'Redundant servers and failover keep the service accessible during component failure, primarily supporting availability.' },
  { id: 'cia-kc-4', objective: '1.2', domain: 1, prompt: 'A company encrypts backups but loses every copy of the encryption key. Which tradeoff does this demonstrate?', options: ['Integrity improved while confidentiality failed', 'Confidentiality improved while availability failed', 'Availability improved while privacy failed', 'All three properties improved'], correctIndex: 1, explanation: 'Encryption protects backup confidentiality, but losing the keys makes authorized recovery impossible and therefore damages availability.' },
  { id: 'cia-kc-5', objective: '1.2', domain: 1, prompt: 'Which outcome most clearly indicates an integrity incident?', options: ['A database becomes temporarily unreachable', 'A confidential file is emailed externally', 'Payment values are altered without approval', 'A server uses excessive memory'], correctIndex: 2, explanation: 'Unauthorized alteration makes the payment data inaccurate and untrustworthy, which is an integrity failure.' },
]

export const ciaTriadSectionQuiz = [
  { id: 'cia-sq-1', objective: '1.2', domain: 1, prompt: 'A ransomware attack encrypts a hospital’s patient records so staff cannot retrieve them. Which CIA property is most immediately affected?', options: ['Confidentiality', 'Integrity', 'Availability', 'Non-repudiation'], correctIndex: 2, explanation: 'The immediate effect is that authorized staff cannot access needed records, making availability the primary concern.' },
  { id: 'cia-sq-2', objective: '1.2', domain: 1, prompt: 'Which safeguard most directly protects confidentiality for data stored on a stolen laptop?', options: ['Full-disk encryption', 'File hashing', 'Load balancing', 'Database replication'], correctIndex: 0, explanation: 'Full-disk encryption helps prevent an unauthorized person from reading stored data when the device is lost or stolen.' },
  { id: 'cia-sq-3', objective: '1.2', domain: 1, prompt: 'A digitally signed software package provides integrity primarily because the recipient can:', options: ['Recover the developer’s private key', 'Detect unauthorized changes to the package', 'Guarantee the server remains online', 'Hide the package from unauthorized users'], correctIndex: 1, explanation: 'Signature verification detects changes made after signing and helps verify the source. It does not provide confidentiality or availability.' },
  { id: 'cia-sq-4', objective: '1.2', domain: 1, prompt: 'A company deploys redundant internet connections from different providers. What risk is it primarily reducing?', options: ['Unauthorized disclosure', 'A single point of failure', 'Unapproved data modification', 'Excessive privilege'], correctIndex: 1, explanation: 'Multiple providers reduce dependence on one connection, improving availability by removing a single point of failure.' },
  { id: 'cia-sq-5', objective: '1.2', domain: 1, prompt: 'Which statement best distinguishes privacy from confidentiality?', options: ['Privacy addresses appropriate handling of personal data; confidentiality limits unauthorized disclosure', 'Privacy applies only to paper records; confidentiality applies to digital records', 'Privacy provides integrity; confidentiality provides availability', 'There is no practical distinction'], correctIndex: 0, explanation: 'Confidentiality prevents unauthorized disclosure, while privacy also concerns whether personal data is collected and used appropriately.' },
  { id: 'cia-sq-6', objective: '1.2', domain: 1, prompt: 'A developer accidentally overwrites correct production configuration values. Which property is primarily affected?', options: ['Integrity', 'Confidentiality', 'Privacy', 'Availability only'], correctIndex: 0, explanation: 'The approved configuration was changed and is no longer accurate. The incident may later affect availability, but integrity is the direct failure.' },
  { id: 'cia-sq-7', objective: '1.2', domain: 1, prompt: 'Why might replication create a confidentiality tradeoff?', options: ['Replicas cannot support availability', 'Every additional copy must also be protected from unauthorized access', 'Replication automatically changes data values', 'Replicas eliminate access controls'], correctIndex: 1, explanation: 'Replication improves availability, but each additional copy expands the data footprint and must receive equivalent confidentiality protection.' },
  { id: 'cia-sq-8', objective: '1.2', domain: 1, prompt: 'Which combination best supports the integrity of financial records?', options: ['Hash verification and controlled change permissions', 'Encryption and redundant power', 'Load balancing and backups only', 'Privacy notices and warning signs'], correctIndex: 0, explanation: 'Hashes can detect changes, while controlled permissions reduce unauthorized modification. Together they directly support integrity.' },
  { id: 'cia-sq-9', objective: '1.2', domain: 1, prompt: 'An online store slows during a traffic spike but remains usable within its service target. What does this illustrate?', options: ['Availability is based on required service levels, not perfect performance', 'Confidentiality always overrides performance', 'Integrity cannot coexist with availability', 'Any slowdown is a total availability failure'], correctIndex: 0, explanation: 'Availability is evaluated against business requirements such as uptime, response time, and recovery objectives—not an impossible promise of zero degradation.' },
  { id: 'cia-sq-10', objective: '1.2', domain: 1, prompt: 'Which question is most useful for identifying the primary CIA property in a scenario?', options: ['Which vendor made the affected product?', 'Was information exposed, changed, or made unreachable?', 'How much did the control cost?', 'Which employee reported the event first?'], correctIndex: 1, explanation: 'Exposure maps to confidentiality, unauthorized change maps to integrity, and inability to access maps to availability.' },
]
