export const threatsReading = [
  'A threat is a circumstance or actor capable of causing harm. A vulnerability is a weakness that can be exploited, and risk combines the likelihood and impact of that exploitation. Keeping these terms separate matters: malware is a threat, an unpatched service is a vulnerability, and the expected business damage is risk. Mitigations reduce likelihood, impact, or both.',
  'Threat actors differ in resources, access, and motivation. Nation-state groups may pursue espionage or disruption. Organized crime commonly seeks money. Hacktivists pursue ideological goals. Insider threats already possess legitimate access and may act maliciously or accidentally. Script kiddies use existing tools with limited sophistication, while shadow IT introduces unmanaged technology without necessarily having malicious intent.',
  'Social engineering manipulates people instead of directly defeating technology. Phishing uses deceptive messages; spear phishing targets a specific person or group; whaling targets senior leaders. Pretexting creates a believable story, baiting offers something desirable, and tailgating follows an authorized person into a restricted area. Urgency, authority, fear, curiosity, and helpfulness are common pressure points.',
  'Malware is categorized by behavior. Ransomware denies access and demands payment. Trojans disguise malicious code as legitimate software. Worms spread without requiring a user to copy them. Spyware collects information, keyloggers capture input, rootkits hide privileged persistence, and botnet agents accept remote commands. Modern attacks often combine several behaviors rather than fitting one clean label.',
  'Password attacks exploit weak credentials and reuse. Brute force tries many values against one account. Password spraying tries a small number of common passwords across many accounts to avoid lockouts. Credential stuffing reuses username-and-password pairs stolen from another service. Offline cracking attacks captured hashes without contacting the live service. MFA, unique passwords, rate limiting, and password managers reduce these risks.',
  'Defenders should match mitigation to attack path. Filtering and awareness can reduce phishing, but strong authentication limits the value of stolen passwords. Patching closes known vulnerabilities, application allow lists restrict unapproved software, segmentation limits spread, and monitoring detects behavior prevention missed. Effective defense assumes that some messages, files, or credentials will bypass the first layer.',
]

export const threatsCards = [
  ['Threat','A circumstance or actor capable of causing harm.'],['Vulnerability','A weakness that can be exploited.'],['Risk','The potential loss resulting from likelihood and impact.'],['Nation-state actor','A state-supported group often pursuing espionage, influence, or disruption.'],['Insider threat','Risk originating from someone with legitimate organizational access.'],['Phishing','Broad deceptive messaging intended to steal information or cause unsafe action.'],['Spear phishing','Phishing tailored to a specific person or group.'],['Pretexting','Using a fabricated identity or story to influence a target.'],['Ransomware','Malware that denies access and demands payment.'],['Trojan','Malware disguised as legitimate or desirable software.'],['Worm','Self-propagating malware that spreads between systems.'],['Password spraying','Trying a few common passwords across many accounts.'],['Credential stuffing','Reusing credentials stolen from another service.'],['Defense in depth','Layered safeguards that reduce dependence on one control.'],
]

export const threatsKnowledgeCheck = [
  {id:'threat-kc-1',objective:'2.1',domain:2,prompt:'An unpatched internet-facing server is best described as what?',options:['Threat actor','Vulnerability','Risk treatment','Impact'],correctIndex:1,explanation:'The missing patch leaves a weakness that may be exploited.'},
  {id:'threat-kc-2',objective:'2.2',domain:2,prompt:'A caller invents an urgent executive request to obtain a password reset. Which technique is used?',options:['Baiting','Pretexting','Tailgating','Typosquatting'],correctIndex:1,explanation:'The attacker builds a fabricated identity and story, which is pretexting.'},
  {id:'threat-kc-3',objective:'2.4',domain:2,prompt:'Which malware can spread between systems without a user copying it?',options:['Worm','Trojan','Logic bomb','Keylogger'],correctIndex:0,explanation:'Worms self-propagate across reachable systems or services.'},
  {id:'threat-kc-4',objective:'2.4',domain:2,prompt:'A few common passwords are tested against thousands of users. What attack is this?',options:['Brute force','Password spraying','Credential stuffing','Hash collision'],correctIndex:1,explanation:'Password spraying spreads a small set of passwords across many accounts.'},
  {id:'threat-kc-5',objective:'2.5',domain:2,prompt:'Why should phishing defenses include MFA as well as filtering?',options:['Filters block every message','Some phishing will bypass filtering','MFA replaces awareness','MFA patches email servers'],correctIndex:1,explanation:'Layering assumes prevention can fail; MFA reduces the usefulness of stolen passwords.'},
]

export const threatsSectionQuiz = [
  {id:'threat-sq-1',objective:'2.1',domain:2,prompt:'Which actor is most likely motivated by ideology?',options:['Hacktivist','Organized crime','Competitor seeking profit','Accidental insider'],correctIndex:0,explanation:'Hacktivists commonly pursue ideological or political goals.'},
  {id:'threat-sq-2',objective:'2.1',domain:2,prompt:'An employee accidentally shares a confidential file publicly. This is what type of threat?',options:['Nation-state','Unintentional insider','Script kiddie','Hacktivist'],correctIndex:1,explanation:'Insider risk includes accidental actions by authorized users.'},
  {id:'threat-sq-3',objective:'2.2',domain:2,prompt:'A tailored email targets the finance director. This is:',options:['Spear phishing','Smishing only','Baiting','Tailgating'],correctIndex:0,explanation:'Spear phishing is customized for a particular person or group.'},
  {id:'threat-sq-4',objective:'2.2',domain:2,prompt:'Following an employee through a secure door without presenting a badge is:',options:['Pretexting','Tailgating','Quishing','Watering hole'],correctIndex:1,explanation:'Tailgating gains physical access by following an authorized person.'},
  {id:'threat-sq-5',objective:'2.4',domain:2,prompt:'Malware disguised as a free utility is most likely a:',options:['Trojan','Worm','Root certificate','Firewall'],correctIndex:0,explanation:'A trojan hides malicious behavior inside apparently legitimate software.'},
  {id:'threat-sq-6',objective:'2.4',domain:2,prompt:'What distinguishes credential stuffing?',options:['It guesses random values','It reuses credentials breached elsewhere','It attacks hashes offline only','It requires physical access'],correctIndex:1,explanation:'Credential stuffing exploits password reuse with previously stolen pairs.'},
  {id:'threat-sq-7',objective:'2.4',domain:2,prompt:'Which malware is designed to hide privileged persistence?',options:['Rootkit','Adware','Worm','Macro'],correctIndex:0,explanation:'Rootkits conceal malicious components and privileged access.'},
  {id:'threat-sq-8',objective:'2.5',domain:2,prompt:'Which control most directly limits malware spreading between network segments?',options:['Segmentation','Password history','Privacy notice','Digital signature on email'],correctIndex:0,explanation:'Segmentation restricts connectivity and lateral movement.'},
  {id:'threat-sq-9',objective:'2.5',domain:2,prompt:'Which pairing best matches weakness and mitigation?',options:['Unpatched service—patch management','Phishing—more shared accounts','Ransomware—disable backups','Credential stuffing—password reuse'],correctIndex:0,explanation:'Patch management closes known software vulnerabilities.'},
  {id:'threat-sq-10',objective:'2.1',domain:2,prompt:'Which statement correctly relates threat, vulnerability, and risk?',options:['A threat exploits a vulnerability to create risk','A vulnerability always causes damage alone','Risk is identical to a threat actor','A mitigation increases likelihood'],correctIndex:0,explanation:'Risk arises when a capable threat may exploit a weakness with resulting impact.'},
]
