export const cryptographyReading = [
  'Cryptography transforms information so security properties can be maintained even across untrusted systems. Encryption primarily protects confidentiality. Hashing supports integrity. Digital signatures provide integrity, source authentication, and non-repudiation. These tools solve different problems, so exam questions often test whether the selected mechanism matches the required outcome.',
  'Symmetric encryption uses the same secret key to encrypt and decrypt. It is fast and efficient for large amounts of data, but the key must be shared securely. AES is a common symmetric algorithm. Losing the key can destroy availability, while exposing it destroys confidentiality for data protected by that key.',
  'Asymmetric encryption uses a mathematically related public and private key pair. The public key can be distributed; the private key must remain controlled by its owner. Data encrypted for confidentiality with a recipient’s public key can be decrypted with the recipient’s private key. Asymmetric operations are slower, so systems commonly use them to exchange a symmetric session key.',
  'A cryptographic hash converts input into a fixed-length digest. A secure hash should be one-way and collision resistant. Hashing does not encrypt data because there is no decryption key. Password systems store salted password hashes so the server can verify a submitted password without storing the original. Salts make identical passwords produce different stored values and reduce precomputed attacks.',
  'Digital signatures reverse the key roles used for confidentiality. The signer uses a private key to sign a digest; others use the corresponding public key to verify it. Verification shows that the signed data has not changed and that the private key produced the signature. It does not hide the signed data. Protecting private signing keys is critical to trust.',
  'Public key infrastructure manages trust at scale. Certificate authorities issue digitally signed certificates that bind public keys to identities. Registration authorities may validate applicants. Certificate status can be checked through certificate revocation lists or OCSP. Trust depends on certificate chains, expiration, intended key usage, and secure protection of root and private keys.',
]

export const cryptographyCards = [
  ['Encryption','Reversible transformation used primarily to protect confidentiality.'],['Symmetric encryption','Encryption using the same shared secret key for encryption and decryption.'],['Asymmetric encryption','Encryption using a related public and private key pair.'],['AES','A widely used symmetric block cipher.'],['Public key','The portion of an asymmetric key pair intended for distribution.'],['Private key','The secret portion of an asymmetric key pair controlled by its owner.'],['Hash','A fixed-length one-way digest used to represent data.'],['Collision resistance','Difficulty of finding two inputs with the same hash.'],['Salt','Unique random data added before password hashing.'],['Digital signature','Private-key operation providing integrity, authentication, and non-repudiation.'],['Certificate','A signed document binding a public key to an identity.'],['Certificate authority','Trusted entity that issues and signs certificates.'],['CRL','A published list of certificates revoked before expiration.'],['OCSP','A protocol for checking certificate status online.'],['PKI','People, policies, hardware, software, and procedures used to manage certificates and public keys.'],
]

export const cryptographyKnowledgeCheck = [
  {id:'crypto-kc-1',objective:'1.4',domain:1,prompt:'Which mechanism primarily protects confidentiality for a large backup file?',options:['Symmetric encryption','Hashing','Digital signature only','Certificate revocation'],correctIndex:0,explanation:'Symmetric encryption efficiently protects the confidentiality of large data sets.'},
  {id:'crypto-kc-2',objective:'1.4',domain:1,prompt:'Which mechanism best detects whether a file changed?',options:['Hash comparison','Load balancing','Token expiration','Data masking only'],correctIndex:0,explanation:'A changed file should produce a different cryptographic digest.'},
  {id:'crypto-kc-3',objective:'1.4',domain:1,prompt:'To encrypt confidential data for a recipient, which key is normally used?',options:['Sender public key','Recipient public key','Recipient private key','CA private key'],correctIndex:1,explanation:'Only the recipient’s private key should decrypt data encrypted with the recipient’s public key.'},
  {id:'crypto-kc-4',objective:'1.4',domain:1,prompt:'What does a salt accomplish in password storage?',options:['Makes identical passwords hash differently','Makes hashing reversible','Replaces the password','Encrypts the database'],correctIndex:0,explanation:'A unique salt changes each password hash and defeats common precomputed tables.'},
  {id:'crypto-kc-5',objective:'1.4',domain:1,prompt:'What does successful digital signature verification provide?',options:['Confidentiality only','Integrity and signer assurance','Availability','Data deletion'],correctIndex:1,explanation:'Verification supports integrity and proves the corresponding private key created the signature.'},
]

export const cryptographySectionQuiz = [
  {id:'crypto-sq-1',objective:'1.4',domain:1,prompt:'What is the main challenge of symmetric encryption?',options:['Securely sharing the secret key','It cannot encrypt large files','It has no algorithms','It always requires certificates'],correctIndex:0,explanation:'Both parties need the same secret key, creating a secure distribution problem.'},
  {id:'crypto-sq-2',objective:'1.4',domain:1,prompt:'Why are hybrid systems common?',options:['Asymmetric methods exchange a symmetric session key efficiently','Hashes decrypt certificates','Symmetric keys create signatures','Public keys are secret'],correctIndex:0,explanation:'Asymmetric cryptography solves key exchange while symmetric cryptography handles bulk data efficiently.'},
  {id:'crypto-sq-3',objective:'1.4',domain:1,prompt:'Which statement about hashing is correct?',options:['It is designed to be one-way','It uses a decryption key','It guarantees availability','It hides message length'],correctIndex:0,explanation:'Secure hashes are one-way digests, not reversible encryption.'},
  {id:'crypto-sq-4',objective:'1.4',domain:1,prompt:'What property makes it difficult to find two inputs with the same digest?',options:['Collision resistance','Key escrow','Forward secrecy','Tokenization'],correctIndex:0,explanation:'Collision resistance describes difficulty finding distinct inputs with equal hashes.'},
  {id:'crypto-sq-5',objective:'1.4',domain:1,prompt:'Which key creates a digital signature?',options:['Signer private key','Signer public key','Recipient public key','CA public key'],correctIndex:0,explanation:'The signer controls the private key; verifiers use the public key.'},
  {id:'crypto-sq-6',objective:'1.4',domain:1,prompt:'Does a digital signature make signed content confidential?',options:['No, encryption is needed for confidentiality','Yes, always','Only after expiration','Only with a hash collision'],correctIndex:0,explanation:'Signatures provide integrity and origin assurance but do not hide content.'},
  {id:'crypto-sq-7',objective:'1.4',domain:1,prompt:'What does a certificate bind together?',options:['Identity and public key','Password and salt','Backup and hash only','Firewall and network'],correctIndex:0,explanation:'A signed certificate associates a subject identity with a public key.'},
  {id:'crypto-sq-8',objective:'1.4',domain:1,prompt:'Which service provides near-real-time certificate status?',options:['OCSP','AES','SHA','RBAC'],correctIndex:0,explanation:'OCSP allows a client to query certificate revocation status online.'},
  {id:'crypto-sq-9',objective:'1.4',domain:1,prompt:'What happens if an encryption key is permanently lost?',options:['Protected data may become unavailable','The data becomes public automatically','Hashes become reversible','Certificates renew themselves'],correctIndex:0,explanation:'Without the required key, authorized users may be unable to recover encrypted data.'},
  {id:'crypto-sq-10',objective:'1.4',domain:1,prompt:'Which component must receive the strongest protection in a CA hierarchy?',options:['Root CA private key','Every public key','Certificate serial number','CRL URL'],correctIndex:0,explanation:'Compromise of the root signing key can undermine trust in the entire hierarchy.'},
]
