export const identityReading = [
  'Identity and access management answers three connected questions: Who is requesting access, what are they allowed to do, and what evidence should be recorded? Authentication verifies an identity claim. Authorization decides which resources and actions that identity may use. Accounting records activity so decisions can be reviewed. Together these functions are often called AAA.',
  'Authentication factors are evidence categories. Something you know includes passwords and PINs. Something you have includes phones, smart cards, and security keys. Something you are includes fingerprints and facial characteristics. Somewhere you are uses location, and something you do can use behavioral patterns. Multifactor authentication requires evidence from at least two different categories; two passwords are still a single factor.',
  'Not every factor resists the same threats. SMS codes can be intercepted or redirected through SIM-swapping. Push notifications can be abused through MFA fatigue. Biometrics cannot be changed easily if compromised and should usually unlock another authenticator rather than serve as a remote secret. Phishing-resistant methods such as hardware security keys and passkeys bind authentication to the legitimate service and reduce credential replay.',
  'Authorization begins after authentication. Role-based access control assigns permissions according to job roles. Attribute-based access control evaluates characteristics such as department, device health, location, data sensitivity, and time. Rule-based systems enforce predefined conditions, while discretionary and mandatory models determine who can set permissions. The best model depends on scale, risk, and governance requirements.',
  'Accounting creates traceability. Authentication logs, access decisions, privileged actions, configuration changes, and data exports should identify who acted, what happened, when it occurred, and whether it succeeded. Reliable timestamps and protected logs support investigations and non-repudiation. Logging everything without review is not enough; organizations need retention, alerting, ownership, and response procedures.',
  'Identity has a lifecycle. Accounts should be provisioned from an approved source, receive only required permissions, be reviewed as responsibilities change, and be disabled promptly when access is no longer needed. Shared accounts weaken accountability. Service accounts require ownership, restricted permissions, protected credentials, and rotation. Strong authentication cannot compensate for excessive authorization or abandoned accounts.',
]

export const identityCards = [
  ['Identification', 'Presenting an identity claim, such as a username.'], ['Authentication', 'Verifying that an identity claim is genuine.'], ['Authorization', 'Determining which resources and actions an identity may access.'], ['Accounting', 'Recording identity and access activity for traceability.'], ['Knowledge factor', 'Something the user knows, such as a password or PIN.'], ['Possession factor', 'Something the user has, such as a phone or security key.'], ['Inherence factor', 'Something the user is, represented by a biometric characteristic.'], ['Multifactor authentication', 'Authentication using evidence from at least two different factor categories.'], ['MFA fatigue', 'Repeated push prompts intended to pressure a user into approving one.'], ['Phishing-resistant authentication', 'Authentication designed to prevent credential use at an impostor service, such as FIDO2 security keys or passkeys.'], ['RBAC', 'Permissions assigned through organizational roles.'], ['ABAC', 'Access decisions based on attributes of subjects, resources, actions, and context.'], ['Account provisioning', 'Creating an account and assigning approved access.'], ['Account deprovisioning', 'Removing or disabling access when it is no longer authorized.'],
]

export const identityKnowledgeCheck = [
  { id:'identity-kc-1',objective:'4.6',domain:4,prompt:'A user enters a password and touches a hardware security key. What does this demonstrate?',options:['Single sign-on','Multifactor authentication','Two-step single-factor authentication','Authorization'],correctIndex:1,explanation:'The password is a knowledge factor and the security key is a possession factor, so two different categories are used.' },
  { id:'identity-kc-2',objective:'4.6',domain:4,prompt:'Which AAA function decides whether an authenticated nurse may open a patient record?',options:['Identification','Authentication','Authorization','Accounting'],correctIndex:2,explanation:'Authorization evaluates what an authenticated identity is permitted to access or do.' },
  { id:'identity-kc-3',objective:'4.6',domain:4,prompt:'Why are two separate passwords not considered MFA?',options:['Passwords cannot be encrypted','Both are knowledge factors','Passwords provide authorization only','MFA requires biometrics'],correctIndex:1,explanation:'MFA requires different factor categories. Two passwords are both something the user knows.' },
  { id:'identity-kc-4',objective:'4.6',domain:4,prompt:'Which access model is best described by permissions assigned to job functions?',options:['RBAC','ABAC','MAC','DAC'],correctIndex:0,explanation:'Role-based access control groups permissions into roles aligned with job responsibilities.' },
  { id:'identity-kc-5',objective:'4.6',domain:4,prompt:'A departed contractor still has an active account. Which lifecycle process failed?',options:['Federation','Deprovisioning','Accounting','Identification'],correctIndex:1,explanation:'Deprovisioning should promptly disable or remove access that is no longer authorized.' },
]

export const identitySectionQuiz = [
  { id:'identity-sq-1',objective:'4.6',domain:4,prompt:'A username primarily performs which function?',options:['Identification','Authentication','Authorization','Accounting'],correctIndex:0,explanation:'A username presents an identity claim; it does not prove the claim is genuine.' },
  { id:'identity-sq-2',objective:'4.6',domain:4,prompt:'Which is a possession factor?',options:['PIN','Fingerprint','Smart card','Typing rhythm'],correctIndex:2,explanation:'A smart card is a physical authenticator the user possesses.' },
  { id:'identity-sq-3',objective:'4.6',domain:4,prompt:'An attacker repeatedly sends login approval prompts. What attack is occurring?',options:['Credential stuffing','MFA fatigue','Password spraying','Typosquatting'],correctIndex:1,explanation:'MFA fatigue attempts to wear down or confuse a user into approving a fraudulent prompt.' },
  { id:'identity-sq-4',objective:'4.6',domain:4,prompt:'Which method is generally most phishing resistant?',options:['SMS code','Email code','Security key using FIDO2','Security questions'],correctIndex:2,explanation:'FIDO2 authenticators bind the response to the legitimate service and resist credential replay at phishing sites.' },
  { id:'identity-sq-5',objective:'4.6',domain:4,prompt:'A policy allows access only from managed devices during business hours. Which model best fits?',options:['RBAC','ABAC','DAC','Passwordless'],correctIndex:1,explanation:'ABAC evaluates contextual attributes such as device state and time.' },
  { id:'identity-sq-6',objective:'4.6',domain:4,prompt:'Which log detail most directly supports accountability?',options:['Screen resolution','Actor identity and timestamp','Device wallpaper','Password length only'],correctIndex:1,explanation:'Attributing an action to an identity at a reliable time provides traceability.' },
  { id:'identity-sq-7',objective:'4.6',domain:4,prompt:'What is the largest accountability problem with shared administrator accounts?',options:['They cannot use encryption','Actions cannot be reliably tied to one person','They prevent role assignment','They eliminate logging'],correctIndex:1,explanation:'Shared credentials make it difficult to determine which person performed an action.' },
  { id:'identity-sq-8',objective:'4.6',domain:4,prompt:'Which practice is most important for service accounts?',options:['Interactive daily use','Unlimited privileges','Named ownership and credential rotation','Shared passwords in documentation'],correctIndex:2,explanation:'Service accounts need accountable ownership, limited permissions, protected secrets, and rotation.' },
  { id:'identity-sq-9',objective:'4.6',domain:4,prompt:'A fingerprint unlocks a cryptographic credential stored on a phone. The fingerprint is what factor?',options:['Knowledge','Possession','Inherence','Location'],correctIndex:2,explanation:'A fingerprint is a biometric characteristic and therefore an inherence factor.' },
  { id:'identity-sq-10',objective:'4.6',domain:4,prompt:'Strong MFA is enabled, but every employee is a database administrator. What remains wrong?',options:['Authentication is too strong','Authorization is excessive','Accounting is impossible','Identification is missing'],correctIndex:1,explanation:'MFA verifies users strongly but does not correct excessive permissions.' },
]
