export const leastPrivilegeReading = [
  'Least privilege means granting only the access required to perform an authorized task, for only as long as it is needed. It applies to people, applications, service accounts, devices, and processes. The goal is not to make work difficult; it is to reduce the damage caused by mistakes, compromised credentials, malicious insiders, and vulnerable software.',
  'Separation of duties divides sensitive workflows so one person cannot complete every critical step alone. One employee may request a payment while another approves it. Dual control requires two authorized participants for an action, while split knowledge ensures no individual possesses an entire secret. These controls reduce fraud and create opportunities to detect error.',
  'Privilege should be temporary when possible. Just-in-time access grants elevated rights only when requested and approved. Just-enough administration provides only the commands needed for a specific task. Privileged access management systems can vault credentials, require approval, record sessions, rotate secrets, and remove access when the task ends.',
  'Zero trust replaces implicit trust with continuous, context-aware decisions. Its shorthand is “never trust, always verify,” but that does not mean distrusting people personally. It means network location alone is not proof of legitimacy. Access decisions should consider identity strength, device health, resource sensitivity, behavior, and current risk, then grant the smallest appropriate scope.',
  'Zero trust architectures use policy decision points to evaluate requests and policy enforcement points to allow, deny, or limit them. Microsegmentation reduces broad network movement. Strong identity, device inventory, telemetry, and automation provide the evidence needed for decisions. Zero trust is an operating model, not a single product that can be purchased and switched on.',
  'Access reviews keep least privilege from decaying. Roles change, projects end, temporary access becomes permanent, and service accounts accumulate permissions. Organizations should review privileged access, remove dormant accounts, detect toxic combinations of duties, and document exceptions. The right question is not only “Can this identity sign in?” but “Should it still have this exact access now?”',
]

export const leastPrivilegeCards = [
  ['Least privilege','Grant only the access required for an authorized task.'],['Separation of duties','Divide critical steps among different people or roles.'],['Dual control','Require two authorized individuals to complete an action.'],['Split knowledge','Divide a secret so no one person knows the entire value.'],['Just-in-time access','Grant elevated privileges temporarily when they are needed.'],['Just-enough administration','Provide only the administrative commands needed for a task.'],['Privileged access management','Control, monitor, and protect powerful accounts and credentials.'],['Zero trust','Continuously evaluate access without granting implicit trust based on location.'],['Policy decision point','Evaluate context and determine whether access should be allowed.'],['Policy enforcement point','Apply the access decision to a connection or resource.'],['Microsegmentation','Create small security zones to limit lateral movement.'],['Implicit trust','Trust granted automatically because of location, network, or prior status.'],['Access review','Periodic validation that permissions remain appropriate.'],['Privilege creep','Accumulation of unnecessary access as roles and projects change.'],
]

export const leastPrivilegeKnowledgeCheck = [
  {id:'priv-kc-1',objective:'1.2',domain:1,prompt:'An analyst can view alerts but cannot change detection rules. Which principle is applied?',options:['Open design','Least privilege','Implicit trust','Non-repudiation'],correctIndex:1,explanation:'The analyst receives only the permissions needed for assigned duties.'},
  {id:'priv-kc-2',objective:'1.2',domain:1,prompt:'One employee creates a vendor and another approves payments. What control is this?',options:['Separation of duties','Single sign-on','Federation','Job rotation only'],correctIndex:0,explanation:'Sensitive steps are split so one person cannot create and pay a fraudulent vendor alone.'},
  {id:'priv-kc-3',objective:'1.2',domain:1,prompt:'Administrative rights expire automatically after one hour. What approach is used?',options:['Just-in-time access','Mandatory vacation','Implicit trust','Password spraying'],correctIndex:0,explanation:'JIT grants privileged access for a limited approved period.'},
  {id:'priv-kc-4',objective:'1.2',domain:1,prompt:'Which statement best describes zero trust?',options:['Trust all internal traffic','Continuously verify context and minimize access','Replace identity systems with firewalls','Block every remote user'],correctIndex:1,explanation:'Zero trust evaluates each request using identity, device, resource, and risk context.'},
  {id:'priv-kc-5',objective:'1.2',domain:1,prompt:'Why are periodic access reviews necessary?',options:['Encryption expires','Privileges can accumulate as roles change','MFA disables accounts','Logs remove permissions'],correctIndex:1,explanation:'Privilege creep leaves identities with access they no longer require.'},
]

export const leastPrivilegeSectionQuiz = [
  {id:'priv-sq-1',objective:'1.2',domain:1,prompt:'A backup service can read files but cannot delete them. This primarily demonstrates:',options:['Least privilege','Job rotation','Non-repudiation','Open access'],correctIndex:0,explanation:'The service receives only the permissions needed for backup work.'},
  {id:'priv-sq-2',objective:'1.2',domain:1,prompt:'Two executives must each provide part of a recovery key. What concept is this?',options:['Split knowledge','Single sign-on','ABAC','Federation'],correctIndex:0,explanation:'No individual holds the entire secret, which is split knowledge.'},
  {id:'priv-sq-3',objective:'1.2',domain:1,prompt:'Which PAM capability most directly improves accountability?',options:['Session recording','Shared passwords','Permanent admin rights','Disabled logging'],correctIndex:0,explanation:'Recorded privileged sessions create evidence of administrative actions.'},
  {id:'priv-sq-4',objective:'1.2',domain:1,prompt:'What is just-enough administration?',options:['Admin access for every employee','Only commands required for the task','Access that never expires','A second password factor'],correctIndex:1,explanation:'JEA limits administrative capability to the minimum command set needed.'},
  {id:'priv-sq-5',objective:'1.2',domain:1,prompt:'An internal device must prove identity and health before each sensitive connection. This reflects:',options:['Implicit trust','Zero trust','Discretionary access only','Security through obscurity'],correctIndex:1,explanation:'Zero trust does not treat internal location as sufficient evidence.'},
  {id:'priv-sq-6',objective:'1.2',domain:1,prompt:'Which technology most directly limits lateral movement?',options:['Microsegmentation','Password history','Full backups','Digital signatures'],correctIndex:0,explanation:'Microsegmentation creates small zones and restricts communication between them.'},
  {id:'priv-sq-7',objective:'1.2',domain:1,prompt:'What does a policy enforcement point do?',options:['Writes the organization policy','Applies an allow or deny decision','Performs annual training','Creates encryption keys only'],correctIndex:1,explanation:'The enforcement point applies the decision to access traffic or resources.'},
  {id:'priv-sq-8',objective:'1.2',domain:1,prompt:'A project ended, but a developer retains production access. This is an example of:',options:['Privilege creep','Dual control','Split knowledge','Tokenization'],correctIndex:0,explanation:'Access accumulated for old duties was not removed when no longer needed.'},
  {id:'priv-sq-9',objective:'1.2',domain:1,prompt:'Which scenario best demonstrates dual control?',options:['One administrator uses two passwords','Two custodians must approve vault access','One user has two roles','A firewall uses two rules'],correctIndex:1,explanation:'Dual control requires two authorized people to complete the sensitive action.'},
  {id:'priv-sq-10',objective:'1.2',domain:1,prompt:'Which is NOT sufficient evidence for a zero trust access decision by itself?',options:['Network location','Identity strength','Device health','Resource sensitivity'],correctIndex:0,explanation:'Zero trust rejects automatic trust based solely on being inside a network.'},
]
