import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Layers3, Sparkles, Trophy } from 'lucide-react'

const typeLabels = { lesson: 'Lesson', flashcards: 'Flashcards', quiz: 'Knowledge check', checkpoint: 'Tier checkpoint' }

export function LessonActivity({ activity, onComplete, completed }) {
  return <><div className="lesson-objective"><span>Domain {activity.domain}</span><span>Objective {activity.objective}</span><span>{activity.duration} min</span></div>{activity.media && <figure className="lesson-media"><img src={activity.media.src} alt={activity.media.alt} /><figcaption>{activity.media.caption}</figcaption></figure>}{activity.learningObjectives && <section className="learning-objectives"><p className="eyebrow">By the end, you can</p>{activity.learningObjectives.map((objective) => <span key={objective}><Check size={14} />{objective}</span>)}</section>}<article className="lesson-body">{activity.content.map((paragraph, index) => <div className="lesson-section" key={paragraph}><span className="lesson-section__number">{String(index + 1).padStart(2, '0')}</span><div className="lesson-section__content">{activity.headings?.[index] && <h2>{activity.headings[index]}</h2>}<p>{paragraph}</p></div></div>)}</article><div className="key-idea"><Sparkles size={19} /><div><strong>Field note</strong><p>Ask what the safeguard protects, how it works, and which risk it reduces. That reasoning transfers better than memorizing labels.</p></div></div><button className="button button--primary activity-complete" onClick={onComplete}>{completed ? <><Check size={17} />Completed — continue</> : <>Mark complete <ArrowRight size={17} /></>}</button></>
}

export function FlashcardActivity({ activity, onComplete, completed }) {
  const [index, setIndex] = useState(0)
  const [flipped, setFlipped] = useState(false)
  const card = activity.cards[index]
  return <><p className="activity-instruction">Tap the card to reveal the meaning. Move at your own pace—this is retrieval practice, not a test.</p><button className={`flashcard ${flipped ? 'flashcard--flipped' : ''}`} onClick={() => setFlipped(!flipped)}><span>{flipped ? 'Definition' : `Term ${index + 1} of ${activity.cards.length}`}</span><strong>{flipped ? card[1] : card[0]}</strong><small>{flipped ? 'Tap to see term' : 'Tap to reveal'}</small></button><div className="flashcard-controls"><button className="button button--ghost" disabled={index === 0} onClick={() => { setIndex(index - 1); setFlipped(false) }}><ArrowLeft size={16} />Previous</button>{index < activity.cards.length - 1 ? <button className="button button--primary" onClick={() => { setIndex(index + 1); setFlipped(false) }}>Next card <ArrowRight size={16} /></button> : <button className="button button--primary" onClick={onComplete}>{completed ? 'Review complete' : 'Complete deck'} <Check size={16} /></button>}</div></>
}

export function QuizActivity({ activity, onComplete }) {
  const [index, setIndex] = useState(0)
  const [selected, setSelected] = useState(null)
  const [correct, setCorrect] = useState(0)
  const [finished, setFinished] = useState(false)
  const question = activity.questions[index]
  const answered = selected !== null
  const choose = (choice) => { if (answered) return; setSelected(choice); if (choice === question.correctIndex) setCorrect(correct + 1) }
  const advance = () => { if (index === activity.questions.length - 1) { setFinished(true); return }; setIndex(index + 1); setSelected(null) }
  if (finished) { const score = Math.round(correct / activity.questions.length * 100); return <div className="activity-results"><div className="results-mark"><Trophy size={38} /></div><p className="eyebrow">{activity.type === 'checkpoint' ? 'Checkpoint complete' : 'Knowledge check complete'}</p><h2>{score >= 80 ? 'Strong signal.' : 'Useful reconnaissance.'}</h2><p>You scored <strong>{correct} of {activity.questions.length}</strong>. Incorrect answers are information, not punishment.</p><div className="results-score"><strong>{score}%</strong><span>accuracy</span></div><button className="button button--primary" onClick={() => onComplete(score / 100)}>Save progress <ArrowRight size={16} /></button></div> }
  return <><div className="quiz-head"><div><p className="eyebrow">Question {index + 1} of {activity.questions.length}</p><span>Domain {question.domain} · Objective {question.objective}</span></div><div className="quiz-dots">{activity.questions.map((_, i) => <i key={i} className={i <= index ? 'active' : ''} />)}</div></div><h2 className="question-title">{question.prompt}</h2><div className="answers">{question.options.map((option, choice) => { let state = ''; if (answered && choice === question.correctIndex) state = 'answer--correct'; else if (answered && choice === selected) state = 'answer--wrong'; return <button key={option} className={`answer ${state}`} onClick={() => choose(choice)}><span>{String.fromCharCode(65 + choice)}</span>{option}{answered && choice === question.correctIndex && <CheckCircle2 size={19} />}</button> })}</div>{answered && <div className={`explanation ${selected === question.correctIndex ? 'explanation--correct' : ''}`}><strong>{selected === question.correctIndex ? 'Correct — clean read.' : 'Not quite. Here’s the distinction.'}</strong><p>{question.explanation}</p></div>}<div className="quiz-footer"><span>{correct} correct so far</span><button className="button button--primary" disabled={!answered} onClick={advance}>{index === activity.questions.length - 1 ? 'See results' : 'Next question'} <ArrowRight size={16} /></button></div></>
}

export function ActivityView({ activity, progress, onClose, onComplete }) {
  const completed = progress.completedActivityIds.includes(activity.id)
  const hasContent = activity.content || activity.cards || activity.questions
  const [readingProgress, setReadingProgress] = useState(0)
  const updateReadingProgress = (event) => { const element = event.currentTarget; const available = element.scrollHeight - element.clientHeight; setReadingProgress(available > 0 ? Math.min(100, Math.round(element.scrollTop / available * 100)) : 100) }
  return <div className="activity-overlay" onScroll={updateReadingProgress}><main className="activity-view"><header className="activity-header"><button className="back-button" onClick={onClose}><ArrowLeft size={16} /> Exit activity</button><span className="activity-header__type">{typeLabels[activity.type]}</span><i className="reading-progress" style={{ width: `${readingProgress}%` }} /></header><div className="activity-shell"><div className="activity-title"><p className="eyebrow">Tier {activity.tierNumber} · {activity.difficulty}</p><h1>{activity.title}</h1><p>{activity.summary}</p></div>{!hasContent ? <div className="preview-state"><Layers3 size={35} /><p className="eyebrow">Curriculum preview</p><h2>This activity has its place on the trail.</h2><p>Its full learning content arrives after the complete Tier 1 experience is validated. You can still explore every tier and see how the path fits together.</p><button className="button button--primary" onClick={onClose}>Return to tier <ArrowRight size={16} /></button></div> : activity.type === 'lesson' ? <LessonActivity activity={activity} completed={completed} onComplete={() => onComplete(activity)} /> : activity.type === 'flashcards' ? <FlashcardActivity activity={activity} completed={completed} onComplete={() => onComplete(activity)} /> : <QuizActivity activity={activity} onComplete={(score) => onComplete(activity, score)} />}</div></main></div>
}
